{{- if .Values.enforcer.enabled -}}
{{- if (semverCompare ">=1.9-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: apps/v1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: DaemonSet
metadata:
  name: neuvector-enforcer-pod
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: neuvector-enforcer-pod
  template:
    metadata:
      labels:
        app: neuvector-enforcer-pod
        release: {{ .Release.Name }}
        {{- with .Values.enforcer.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.enforcer.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- if .Values.systemSettings.imagePullSecret.enabled }}
      imagePullSecrets:
        - name: neuvector-image-pull-secret
    {{- end }}
      tolerations:
{{- if .Values.enforcer.tolerateControlPlane }}
{{- include "neuvector.ctlplaneTolerations" . | nindent 8 }}
{{- end }}
{{- if .Values.enforcer.tolerations }}
{{ toYaml .Values.enforcer.tolerations | indent 8 }}
{{- end }}
      hostPID: true
      serviceAccountName: {{ .Values.serviceAccount }}
      serviceAccount: {{ .Values.serviceAccount }}
      containers:
        - name: neuvector-enforcer-pod
          image: {{ template "system_default_registry" . }}{{ .Values.enforcer.image.repository }}:{{ .Values.enforcer.image.tag }}
          imagePullPolicy: {{ .Values.enforcer.image.pullPolicy | default "Always" }}
          securityContext:
            privileged: true
          resources:
          {{- if .Values.enforcer.resources }}
{{ toYaml .Values.enforcer.resources | indent 12 }}
          {{- end }}
          env:
            - name: CLUSTER_JOIN_ADDR
              value: neuvector-svc-controller.{{ .Release.Namespace }}
            - name: CLUSTER_ADVERTISED_ADDR
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CLUSTER_BIND_ADDR
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          {{- if .Values.platformInfo }}
            - name: NV_PLATFORM_INFO
              value: "platform={{ .Values.platformInfo }}"
          {{- end }}
          volumeMounts:
            - mountPath: {{ include "neuvector.criVolumeMount" . }}
              name: runtime-sock
              readOnly: true
            - mountPath: /host/proc
              name: proc-vol
              readOnly: true
            - mountPath: /host/cgroup
              name: cgroup-vol
              readOnly: true
            - mountPath: /lib/modules
              name: modules-vol
              readOnly: true
          {{- if .Values.enforcer.internal.certificate.secret }}
            - mountPath: /etc/neuvector/certs/internal/cert.key
              subPath: {{ .Values.enforcer.internal.certificate.keyFile }}
              name: internal-cert
              readOnly: true
            - mountPath: /etc/neuvector/certs/internal/cert.pem
              subPath: {{ .Values.enforcer.internal.certificate.pemFile }}
              name: internal-cert
              readOnly: true
            - mountPath: /etc/neuvector/certs/internal/ca.cert
              subPath: {{ .Values.enforcer.internal.certificate.caFile }}
              name: internal-cert
              readOnly: true
          {{- end }}
      terminationGracePeriodSeconds: 1200
      restartPolicy: Always
      volumes:
        - name: runtime-sock
          hostPath:
            path: {{ include "neuvector.criVolume" . }}
        - name: proc-vol
          hostPath:
            path: /proc
        - name: cgroup-vol
          hostPath:
            path: /sys/fs/cgroup
        - name: modules-vol
          hostPath:
            path: /lib/modules
      {{- if .Values.enforcer.internal.certificate.secret }}
        - name: internal-cert
          secret:
            secretName: {{ .Values.enforcer.internal.certificate.secret }}
      {{- end }}
{{- end }}