apiVersion: v1
kind: ConfigMap
metadata:
  name: neuvector-init
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- if not .Values.systemSettings.createAsSecret.enabled }}
  {{ print "sysinitcfg.yaml: |" -}}
  {{ include "neuvector.sysinitcfg" . | nindent 4 }}
  {{- end }}
  {{- if and (.Values.customUserRoles.enabled) (not .Values.customUserRoles.createAsSecret.enabled) }}
  {{ print "roleinitcfg.yaml: |" -}}
  {{ include "neuvector.roleinitcfg" . | nindent 4 }}
  {{- end }}
  {{- if and (.Values.localPasswordProfile.enabled) (not .Values.localPasswordProfile.createAsSecret.enabled) }}
  {{ print "passwordprofileinitcfg.yaml: |" -}}
  {{ include "neuvector.passwordprofileinitcfg" . | nindent 4 }}
  {{- end }}