{{- with .Values.monitoring }}
{{- if and .enabled .exporter.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    neuvector-account-role: reader
  name: neuvector-prometheus-exporter-pod-secret
  namespace: {{ $.Release.Namespace }}
  labels:
    chart: {{ template "neuvector.chart" $ }}
    heritage: {{ $.Release.Service }}
    release: {{ $.Release.Name }}
type: Opaque
data:
  CTRL_USERNAME: {{ .exporter.credentials.Fullname | b64enc | quote }}
  CTRL_PASSWORD: {{ .exporter.credentials.Password | b64enc | quote }}
{{- end }}
{{- end }}