apiVersion: v1
kind: Secret
metadata:
  name: neuvector-init
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- if .Values.externalAuthProvider.enabled }}
  {{ printf "%sinitcfg.yaml:" .Values.externalAuthProvider.provider }}
  {{ print .Values.externalAuthProvider.config | b64enc | indent 2 }}
  {{- end }}
  {{- if or .Values.localUsers.enabled .Values.monitoring.enabled .Values.systemSettings.createLocalAdmin.create }}
  {{ print "userinitcfg.yaml:" -}}
  {{ include "neuvector.userinitcfg" . | b64enc | nindent 4 }}
  {{- end }}
  {{- if .Values.systemSettings.createAsSecret.enabled }}
  {{ print "sysinitcfg.yaml:" -}}
  {{ include "neuvector.sysinitcfg" . | b64enc | nindent 4 }}
  {{- end }}
  {{- if and (.Values.customUserRoles.enabled) (.Values.customUserRoles.createAsSecret.enabled) }}
  {{ print "roleinitcfg.yaml:" -}}
  {{ include "neuvector.roleinitcfg" . | b64enc | nindent 4 }}
  {{- end }}
  {{- if and (.Values.localPasswordProfile.enabled) (.Values.localPasswordProfile.createAsSecret.enabled) }}
  {{ print "passwordprofileinitcfg.yaml:" -}}
  {{ include "neuvector.passwordprofileinitcfg" . | b64enc | nindent 4 }}
  {{- end }}